export type Article={slug:string;category:string;title:string;excerpt:string;date:string;readTime:string;image:string;imageAlt:string;credit:string;creditUrl:string;intro:string;sections:{heading:string;paragraphs:string[];bullets?:string[]}[]};
export const articles:Article[]=[
{slug:'best-washable-dog-beds',category:'HOME',title:'How to choose a washable dog bed that lasts',excerpt:'A practical framework for finding supportive, easy-clean sleep space—without replacing it every season.',date:'August 20, 2026',readTime:'8 min read',image:'https://images.unsplash.com/photo-1760907217075-19ec3a32c114?auto=format&fit=crop&fm=jpg&q=82&w=1800',imageAlt:'A dog sleeping peacefully in a cozy bed',credit:'Peyton Clough',creditUrl:'https://unsplash.com/photos/I9ofPomR0zg',intro:'A dog bed has a deceptively hard job. It must cushion joints, survive digging and circling, resist odor, and still fit inside a washing machine. The best choice is less about a fashionable shape and more about how the bed is built—and how easily every layer can be cleaned.',sections:[
{heading:'Start with your dog’s sleeping style',paragraphs:['Watch where your dog naturally settles for a few days. Dogs that curl tightly often enjoy bolstered sides, while sprawlers need a broad, flat surface. Dogs that move between warm and cool spots may prefer a breathable mat over deep faux fur.','Measure your dog from nose to tail while relaxed, then add 8 to 12 inches. A bed that looks roomy in product photography can feel cramped once a large dog stretches out.']},
{heading:'Look beneath the cover',paragraphs:['For daily use, a removable cover is the minimum. A separate waterproof liner protects the foam from accidents and damp fur. Zippers should be covered or placed where chewing paws cannot easily reach them.','Solid foam usually holds its shape better than loose fill. Senior dogs and larger breeds often benefit from a supportive foam base that does not bottom out when you press a hand into the center.'],bullets:['Removable, machine-washable outer cover','Water-resistant inner liner','Non-slip bottom for hard floors','Replacement covers sold separately','Clear washing and drying instructions']},
{heading:'Make wash day realistic',paragraphs:['Check the cover dimensions against your washer, not just the bed dimensions. Oversized bolsters can overwhelm a standard machine even when the label says washable. Beds with removable bolster inserts are easier to clean and dry thoroughly.','Vacuum weekly, wash the cover according to its label, and let every component dry completely before reassembly. Keeping a spare cover makes the routine much easier in wet weather.']},
{heading:'Our bottom line',paragraphs:['Prioritize construction over trendy fabric. A well-sized bed with a durable cover, protected foam, and available replacement parts is usually the better long-term value. If your dog has arthritis, mobility changes, or persistent stiffness, ask your veterinarian what support is appropriate.']}]},
{slug:'calmer-indoor-cat-setup',category:'CATS',title:'A calmer indoor cat setup, room by room',excerpt:'Create a home that supports climbing, hiding, scratching, play, and uninterrupted rest.',date:'August 16, 2026',readTime:'7 min read',image:'https://images.unsplash.com/photo-1764440858893-91657e228cee?auto=format&fit=crop&fm=jpg&q=82&w=1800',imageAlt:'A fluffy cat sitting beside a window',credit:'Oksana Lysenko',creditUrl:'https://unsplash.com/photos/IglUQN7LUio',intro:'Indoor cats do best when their environment gives them choices. A beautiful cat tree in one corner is helpful, but calm usually comes from a network of small resources: elevated observation spots, quiet hiding places, appropriate scratching surfaces, predictable play, and litter boxes that feel safe to use.',sections:[
{heading:'Think in zones, not products',paragraphs:['Map your cat’s day. Where do they watch activity, retreat from noise, scratch after waking, and wait for meals? Place resources where the behavior already happens instead of forcing everything into one “cat area.”','Vertical space expands a small home. A stable tower, cleared shelf, or secure window perch lets a cat observe without being in the middle of foot traffic.']},
{heading:'Build a better litter setup',paragraphs:['Choose a quiet, accessible location with more than one exit route when possible. Boxes beside loud appliances or in corners where another pet can block access may be avoided.','Many cats prefer a generous uncovered box with unscented litter. Scoop at least daily and wash with mild, fragrance-free soap. For multi-cat homes, a common starting point is one box per cat plus one extra, distributed across different locations.'],bullets:['Large enough to turn around comfortably','Easy entry for kittens or older cats','Unscented litter and cleaner','A mat that does not trap sensitive paws']},
{heading:'Offer the right kind of scratching',paragraphs:['Scratching is normal communication and body care. Place a tall, sturdy vertical post near sleeping areas and a horizontal scratcher near high-traffic rooms. Stability matters more than ornament: if it wobbles, many cats will return to the sofa.','Reward exploration with treats or play, but do not place paws on the surface. Cats learn faster when the preferred option is convenient and satisfying.']},
{heading:'Create a predictable rhythm',paragraphs:['Two or three short interactive play sessions can be more engaging than leaving toys out all day. Rotate toys, end play with a small meal or treat, and protect a few uninterrupted sleep areas.','Sudden hiding, litter-box changes, aggression, or loss of appetite can signal illness as well as stress. Contact a veterinarian when behavior changes are abrupt or persistent.']}]},
{slug:'comfortable-leash-walking',category:'WALKS',title:'Comfortable leash walking starts before the sidewalk',excerpt:'Fit the gear, lower the distractions, and teach the simple check-ins that make walks easier.',date:'August 10, 2026',readTime:'9 min read',image:'https://images.unsplash.com/photo-1777301411375-250fd323b53f?auto=format&fit=crop&fm=jpg&q=82&w=1800',imageAlt:'A dog being walked on a leash outdoors',credit:'Roman',creditUrl:'https://unsplash.com/photos/WksbmSyN_ZE',intro:'Leash pulling is rarely solved by buying one magic harness. Comfortable walks come from a good fit, a manageable environment, and many small moments in which the dog learns that staying connected to you makes the walk continue.',sections:[
{heading:'Fit the equipment first',paragraphs:['A harness should sit securely without rubbing behind the front legs or restricting shoulder movement. You should be able to slide two fingers beneath the straps, while the dog should not be able to back out of it.','Recheck fit after haircuts, coat changes, and growth. Pair a standard fixed-length leash with a secure ID tag. Retractable leashes can make distance and tension harder to manage in busy spaces.'],bullets:['Multiple adjustment points','Smooth edges around the chest and armpits','A secure buckle and sturdy attachment ring','Reflective details for low-light walks']},
{heading:'Practice where success is easy',paragraphs:['Begin indoors or in a quiet driveway. Mark and reward when your dog turns toward you, walks beside you for a few steps, or follows gentle leash pressure. Keep sessions short enough that both of you finish well.','Outside, start with a low-distraction route. A dog who cannot take a favorite treat may be too excited or worried to learn. Add distance from the trigger rather than pulling closer.']},
{heading:'Use sniffing as part of the walk',paragraphs:['Sniffing is not wasted time. Letting a dog investigate safe areas can make a walk more satisfying and lower the pressure to cover a long distance. Use a cue such as “go sniff” so exploration becomes a reward for a few connected steps.','When the leash tightens, stop or calmly change direction. Move forward again when slack returns. Consistency matters more than speed.']},
{heading:'Know when to get help',paragraphs:['If your dog lunges, panics, freezes, or redirects biting toward the leash or handler, work with a qualified reward-based trainer or veterinary behavior professional. Pain can also change walking behavior, so sudden reluctance or gait changes deserve a veterinary check.']}]},
{slug:'pet-friendly-road-trip',category:'TRAVEL',title:'The practical pet-friendly road-trip checklist',excerpt:'Plan safer rest stops, calmer car time, and an arrival routine that helps pets settle.',date:'August 4, 2026',readTime:'10 min read',image:'https://images.unsplash.com/photo-1559190394-df5a28aab5c5?auto=format&fit=crop&fm=jpg&q=82&w=1800',imageAlt:'A dog riding in a car on a road trip',credit:'Ja San Miguel',creditUrl:'https://unsplash.com/photos/_-QQuvAwQ-0',intro:'A successful road trip begins well before the luggage goes into the trunk. The safest, calmest journeys use familiar restraint, gradual practice, verified pet policies, and a travel kit that keeps essentials within reach—not buried under suitcases.',sections:[
{heading:'Practice the car in small steps',paragraphs:['Start with brief sessions in a parked car, then take a short trip to a pleasant destination. Gradually build duration while watching for drooling, panting, trembling, vomiting, or frantic movement.','If your pet becomes carsick or highly distressed, speak with a veterinarian before the trip. Do not give human motion-sickness or calming medication unless specifically directed.']},
{heading:'Use secure restraint',paragraphs:['Pets should not ride loose or in the front seat. Use a properly secured travel crate or a crash-tested restraint appropriate for the animal and vehicle. Keep heads and paws inside the car.','Attach identification to a collar or harness and confirm the microchip registration is current. Carry a recent photo and copies of relevant health records.']},
{heading:'Pack the reachable bag',paragraphs:['Put one small bag where a passenger can reach it without unloading the car. Bring more food and medication than the trip requires in case of delays. Use water from home at first if your pet is sensitive to changes.'],bullets:['Water, bowls, food, treats, and medications','Leash, harness, waste bags, and litter supplies','Bedding or a familiar blanket','Towels, pet-safe wipes, and cleanup bags','Veterinary records and emergency contacts']},
{heading:'Plan stops and arrival',paragraphs:['Choose safe rest areas before departure and offer breaks at intervals appropriate for your pet. Never leave an animal unattended in a parked vehicle; temperatures can become dangerous quickly even when the weather feels mild.','At the destination, set up food, water, litter, and a quiet resting area before opening the carrier. Keep the first hour calm and inspect fences, balconies, doors, and local hazards before allowing exploration.']}]}
];
export function getArticle(slug:string){return articles.find(a=>a.slug===slug)}
